### ISSUE TITLE
Python 3.9 + Bug

### ISSUE THREAD

**Issue by Isaac-Flath** [fastai/nbprocess#81] opened 2022-06-22 13:27 UTC
@jph00 

I can't get nbprocess to work with python 3.9+.  I am not sure if 3.9+ is intentionally unsupported or not, but thought I would open an issue to be on the safe side.

I did upgrade both nbprocess + fastcore to the latest - and this was happening on a new project created yesterday via `nbprocess_new` in a new git repo.

**Repo with library this happened on:** https://github.com/Isaac-Flath/trading-testing

# What I think is a part of the issue

I believe it is because `setup.py` has this, which does not include anything above `3.8`.  

`py_versions = '2.0 2.1 2.2 2.3 2.4 2.5 2.6 2.7 3.0 3.1 3.2 3.3 3.4 3.5 3.6 3.7 3.8'.split()`

In my `settings.ini` I had `min_python = 3.9`, but after rebuilding the library this was still not included in the `setup.py` file.  Should `py_versions` in `setup.py` be updated based on what is in `min_python` version in `settings.ini`?

EDIT:  I can fix this by going to 3.8, or fix it in 3.9 by adding 3.9 to the `py_versions` variable.

# Stack Traces

Here's the particular stack traces.  Changing to a `3.8` conda environment fixed these and it worked just fine in `3.8`.  These are in my python 3.9 environment (p39).

**When running `make docs` in python 3.9 environment**
```bash
(p39) isaacflath@Isaacs-MacBook-Pro trading-testing % make docs            
nbprocess_export
nbprocess_quarto
Traceback (most recent call last):
  File "/Users/isaacflath/opt/miniconda3/envs/p39/bin/nbprocess_quarto", line 33, in <module>
    sys.exit(load_entry_point('nbprocess', 'console_scripts', 'nbprocess_quarto')())
  File "/Users/isaacflath/opt/miniconda3/envs/p39/bin/nbprocess_quarto", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/Users/isaacflath/opt/miniconda3/envs/p39/lib/python3.9/importlib/metadata.py", line 86, in load
    module = import_module(match.group('module'))
  File "/Users/isaacflath/opt/miniconda3/envs/p39/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/isaacflath/github/nbprocess/nbprocess/cli.py", line 10, in <module>
    from .processors import *
  File "/Users/isaacflath/github/nbprocess/nbprocess/processors.py", line 14, in <module>
    from .lookup import *
  File "/Users/isaacflath/github/nbprocess/nbprocess/lookup.py", line 53, in <module>
    nbprocess_lookup = NbdevLookup(_libs())
  File "/Users/isaacflath/github/nbprocess/nbprocess/lookup.py", line 48, in _libs
    modidx = import_module(f"{get_config()['lib_name']}._modidx")
  File "/Users/isaacflath/opt/miniconda3/envs/p39/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named 'tradingtesting'
make: *** [docs] Error 1
```

**When running `pip install -e .` in python 3.9 conda env**

```bash
(p39) isaacflath@Isaacs-MacBook-Pro trading-testing % make install_py
nbprocess_export
pip install -e ".[dev]"
Obtaining file:///Users/isaacflath/github/trading-testing
    ERROR: Command errored out with exit status 1:
     command: /Users/isaacflath/opt/miniconda3/envs/p39/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/Users/isaacflath/github/trading-testing/setup.py'"'"'; __file__='"'"'/Users/isaacflath/github/trading-testing/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/vs/j71s84gs4f7d059xxqrf71wc0000gn/T/pip-pip-egg-info-xr9u03w8
         cwd: /Users/isaacflath/github/trading-testing/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/Users/isaacflath/github/trading-testing/setup.py", line 39, in <module>
        ] + ['Programming Language :: Python :: '+o for o in py_versions[py_versions.index(min_python):]] + (['License :: ' + lic[1] ] if lic[1] else []),
    ValueError: '3.9' is not in list
    ----------------------------------------
WARNING: Discarding file:///Users/isaacflath/github/trading-testing. Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
make: *** [install_py] Error 1
```

**Comment by muellerzr** [comment] 2022-06-22 16:34
Though the CI runs on py 3.10 @Isaac-Flath so I think it's just that the list needs updating: https://github.com/fastai/nbprocess/blob/master/.github/workflows/test.yaml#L16

(For your version issue. The other error is a duplicate of 80)

**Comment by Isaac-Flath** [comment] 2022-06-22 18:06
Thanks!  I believe both of these are the same cause.  Switching to python 3.8 fixes both stack traces above.

Once it can do the editable install of the lib, it is able to then find the library and all works well.

**Comment by Isaac-Flath** [comment] 2022-06-22 18:21
As a new note - I am able to clear both in python 3.9 by adding 3.9 to the setup.py `py_versions` variable

**Comment by hamelsmu** [comment] 2022-06-22 20:09
@Isaac-Flath I added the this to `setup.py` in 0ed967d6779d2e47c355be7f414e21b9e0c7f748

**Comment by hamelsmu** [comment] 2022-06-22 20:18
I've added `make docs` to the tests with different python versions, a run is now happening here: https://github.com/fastai/nbprocess/actions/runs/2544891736 

If that clears we can close this issue.

**Comment by hamelsmu** [comment] 2022-06-22 20:43
I confirmed that `make docs` works for all versions of python in https://github.com/fastai/nbprocess/pull/83

Closing this

**Closed by hamelsmu** 2022-06-22 20:43 UTC
